// <auto-generated />
using System;
using Aurum.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aurum.Infrastructure.Migrations
{
    [DbContext(typeof(AurumDbContext))]
    partial class AurumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aurum.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Guid");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("Aurum.Domain.Entities.Transactions", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryGuid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.Property<Guid>("WalletGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("WalletType")
                        .HasColumnType("integer");

                    b.HasKey("Guid");

                    b.HasIndex("CategoryGuid");

                    b.HasIndex("CreatedByGuid");

                    b.HasIndex("WalletGuid");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("Aurum.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Aurum.Domain.Entities.Wallet", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserGuid")
                        .HasColumnType("uuid");

                    b.Property<string>("WalletType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Guid");

                    b.HasIndex("UserGuid");

                    b.ToTable("Wallets");

                    b.HasDiscriminator<string>("WalletType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Aurum.Domain.Entities.Members", b =>
                {
                    b.HasBaseType("Aurum.Domain.Entities.User");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WalletGuid")
                        .HasColumnType("uuid");

                    b.Property<int>("WalletRole")
                        .HasColumnType("integer");

                    b.HasIndex("WalletGuid");

                    b.HasDiscriminator().HasValue("Members");
                });

            modelBuilder.Entity("Aurum.Domain.Entities.PrivateWallet", b =>
                {
                    b.HasBaseType("Aurum.Domain.Entities.Wallet");

                    b.Property<Guid>("OwnerGuid")
                        .HasColumnType("uuid");

                    b.HasIndex("OwnerGuid");

                    b.HasDiscriminator().HasValue("Private");
                });

            modelBuilder.Entity("Aurum.Domain.Entities.SharedWallet", b =>
                {
                    b.HasBaseType("Aurum.Domain.Entities.Wallet");

                    b.Property<Guid>("OwnerGuide")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerUserGuid")
                        .HasColumnType("uuid");

                    b.HasIndex("OwnerUserGuid");

                    b.HasDiscriminator().HasValue("Public");
                });

            modelBuilder.Entity("Aurum.Domain.Entities.Transactions", b =>
                {
                    b.HasOne("Aurum.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aurum.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByGuid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Aurum.Domain.Entities.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("CreatedBy");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Aurum.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("Aurum.Domain.Entities.User", null)
                        .WithMany("Wallets")
                        .HasForeignKey("UserGuid");
                });

            modelBuilder.Entity("Aurum.Domain.Entities.Members", b =>
                {
                    b.HasOne("Aurum.Domain.Entities.SharedWallet", "SharedWallet")
                        .WithMany("Members")
                        .HasForeignKey("WalletGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SharedWallet");
                });

            modelBuilder.Entity("Aurum.Domain.Entities.PrivateWallet", b =>
                {
                    b.HasOne("Aurum.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("OwnerGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Aurum.Domain.Entities.SharedWallet", b =>
                {
                    b.HasOne("Aurum.Domain.Entities.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("Aurum.Domain.Entities.User", b =>
                {
                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("Aurum.Domain.Entities.Wallet", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Aurum.Domain.Entities.SharedWallet", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
