version: "3.9"
services:
  app:
    build: .
    container_name: ${DOCKER_REGISTRY-}api_whatsapp_aurum
    restart: always
    env_file: 
      - .env
    ports:
      - "3000:3000"

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ${DOCKER_REGISTRY-}expose_ngrok
    restart: always
    command: http app:3000
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    ports:
      - "8080:8080"
      - "4040:4040"